name: Release Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: pnpm docs:build
      - name: Create Tarball
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: ${{ github.workspace }}/.vitepress/
          files: |
            ./dist
          outPath: ${{ github.workspace }}/.vitepress/clab-docs-${{ github.ref_name }}.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/.vitepress/clab-docs-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
